### ISSUE TITLE
`proton-vpn-gtk-app` beta on Arch linux

### ISSUE THREAD

**Issue by BIGBEASTISHANK** [ProtonVPN/proton-vpn-gtk-app#36]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [x] I have searched open and closed issues for duplicates
- [ ] This isn't a feature request
- [x] This is not a report about my app not working as expected

----------------------------------------

Just wondering when we can gat beta application on arch linux? Like we dont even have a beta branch on github so Just asking.

**Comment by LuigiARC** [comment]
*(I do not work at Proton)*
Proton has stated before that Arch isn't an OS they are officiallty willing to support at the moment due to the number of employees they have on this. As such, I don't know whether making this type of issue in their repo is appropriate. 
> We’d love to support the new app for arch Linux but honestly we’re understaffed and don’t have the bandwidth to be supporting the same distros that we did before with the previous client (4 packages before vs 10 packages now). If anyone from the community is willing to make AUR packages for themselves and publish/maintain them we’re totally fine with that, as long as people keep in mind that it would be an unofficial version because we currently don’t support arch Linux with the new v4 app. 

- Source: https://www.reddit.com/r/ProtonVPN/comments/17clwac/comment/k5r1qdg/?utm_source=share&utm_medium=mweb3x&utm_name=mweb3xcss&utm_term=1&utm_content=share_button

Nevertherless, you probably know that there is a community-maintained AUR listing that allows you to install this on Arch. If you want the beta from the other issue, I'm sure there's a way to get it by either by downloading and changing the PKGBUILD from the AUR for the files in their server or by manually installing the dependencies and building since it's all Python.

I don't currently have the necessary knowledge or time to figure out makepkg or manually compiling/building python at the moment, so I'll just wait until the commits are pushed to this repo to update my app directly from the AUR package :)

### Here's the direct link to the PKGBUILD from the AUR if you want to play around with it:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=proton-vpn-gtk-app

**Comment by BIGBEASTISHANK** [comment]
Well I asked from aur maintainer alimolaei, but I didn't saw that reddit post it's ok and i totally understand, if someday I learn how to convert those beta files to arch i will also try my best to do it. Currently I don't have that amount of knowledge 😊 closing the issue.
